version: 0.0
os: linux

files:
  - source: disk/shop/
    destination: /var/www/html
file_exists_behavior: OVERWRITE

#hooks:
  #BeforeInstall:
  #AfterInstall:
    #- location: scripts/restart_httpd.sh
      #timeout: 300
