version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/install_httpd.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_httpd.sh
      timeout: 300
      runas: root
