version: 0.2

phases:
  install:
    commands:
      - echo "Install dependencies"
      - npm install
  build:
    commands:
      - echo "Build project"
      - npm run build

artifacts:
  base-directory: dist
  files:
    - '**/*'
