version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Install dependencies"
      - npm install
  build:
    commands:
      - echo "Build vue app"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
